version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.32
    - 14.14.39
    - 14.14.41
    - 15.0.0
  - dependency-name: sass
    versions:
    - 1.32.11
  - dependency-name: "@testing-library/user-event"
    versions:
    - 12.8.1
    - 13.0.0
    - 13.0.1
    - 13.0.10
    - 13.0.13
    - 13.0.2
    - 13.0.7
    - 13.1.1
    - 13.1.2
    - 13.1.3
    - 13.1.5
  - dependency-name: "@types/jest"
    versions:
    - 26.0.21
